package cli

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/gofrs/flock"
	"goark.dev/cli/internal/generate"
)

// GenerationResult 描述一个 package 的生成输出。
type GenerationResult struct {
	Generator string
	Package   string
	Output    string
	Changed   bool
	Removed   bool
}

type projectGenerator interface {
	Name() string
	Generate(project goarkProject, dryRun bool) ([]GenerationResult, error)
}

type annotationProjectGenerator struct{}

func (annotationProjectGenerator) Name() string {
	return "annotations"
}

func (g annotationProjectGenerator) Generate(project goarkProject, dryRun bool) ([]GenerationResult, error) {
	packages := append([]goPackage(nil), project.Packages...)
	sort.Slice(packages, func(i, j int) bool {
		return packages[i].ImportPath < packages[j].ImportPath
	})
	results := make([]GenerationResult, 0)
	for _, item := range packages {
		hasAnnotations, err := packageContainsGoarkAnnotations(item)
		if err != nil {
			return nil, fmt.Errorf("检查 package %s 的 Goark 注解失败: %w", item.ImportPath, err)
		}
		if !hasAnnotations {
			stale, err := staleAnnotationGenerationResult(g.Name(), item, dryRun)
			if err != nil {
				return nil, err
			}
			if stale != nil {
				results = append(results, *stale)
			}
			continue
		}
		source, err := generate.GenerateAnnotations(generate.AnnotationScanSpec{
			Dir:         item.Dir,
			PackageName: item.Name,
			Files:       append(append([]string(nil), item.GoFiles...), item.CgoFiles...),
		})
		if err != nil {
			return nil, fmt.Errorf("生成 package %s 的 Goark 注解代码失败: %w", item.ImportPath, err)
		}
		output := filepath.Join(item.Dir, generate.DefaultAnnotationOutputName(item.Name))
		result := GenerationResult{
			Generator: g.Name(),
			Package:   item.ImportPath,
			Output:    output,
		}
		if !dryRun {
			changed, err := writeGeneratedFile(output, source)
			if err != nil {
				return nil, fmt.Errorf("写入 package %s 的生成代码失败: %w", item.ImportPath, err)
			}
			result.Changed = changed
		}
		results = append(results, result)
	}
	return results, nil
}

func staleAnnotationGenerationResult(generatorName string, item goPackage, dryRun bool) (*GenerationResult, error) {
	output := filepath.Join(item.Dir, generate.DefaultAnnotationOutputName(item.Name))
	data, err := os.ReadFile(output)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("检查 package %s 的陈旧生成文件失败: %w", item.ImportPath, err)
	}
	if !bytes.HasPrefix(data, []byte("// Code generated by goark; DO NOT EDIT.\n")) {
		return nil, nil
	}
	result := &GenerationResult{
		Generator: generatorName,
		Package:   item.ImportPath,
		Output:    output,
		Removed:   true,
	}
	if dryRun {
		return result, nil
	}
	if err := os.Remove(output); err != nil {
		return nil, fmt.Errorf("删除 package %s 的陈旧生成文件失败: %w", item.ImportPath, err)
	}
	return result, nil
}

func generateProject(project goarkProject, dryRun bool) (results []GenerationResult, resultErr error) {
	if !dryRun {
		unlock, err := lockProjectGeneration(project.Root)
		if err != nil {
			return nil, err
		}
		defer func() {
			if err := unlock(); err != nil && resultErr == nil {
				resultErr = fmt.Errorf("释放项目生成锁失败: %w", err)
			}
		}()
	}
	generators := []projectGenerator{annotationProjectGenerator{}}
	results = make([]GenerationResult, 0)
	for _, generator := range generators {
		generated, err := generator.Generate(project, dryRun)
		if err != nil {
			return nil, err
		}
		results = append(results, generated...)
	}
	return results, nil
}

func lockProjectGeneration(root string) (func() error, error) {
	lockRoot := filepath.Join(os.TempDir(), "goark-generation-locks")
	if err := os.MkdirAll(lockRoot, 0o700); err != nil {
		return nil, fmt.Errorf("创建生成锁目录失败: %w", err)
	}
	canonicalRoot, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("解析项目根目录失败: %w", err)
	}
	digest := sha256.Sum256([]byte(normalizeGenerationLockRoot(canonicalRoot)))
	lock := flock.New(filepath.Join(lockRoot, hex.EncodeToString(digest[:])+".lock"))
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	locked, err := lock.TryLockContext(ctx, 25*time.Millisecond)
	if err != nil {
		return nil, fmt.Errorf("获取项目生成锁失败: %w", err)
	}
	if !locked {
		return nil, fmt.Errorf("等待项目生成锁超时: %s", canonicalRoot)
	}
	return lock.Unlock, nil
}

func packageContainsGoarkAnnotations(item goPackage) (bool, error) {
	files := make([]string, 0, len(item.GoFiles)+len(item.CgoFiles))
	files = append(files, item.GoFiles...)
	files = append(files, item.CgoFiles...)
	for _, name := range files {
		path := filepath.Join(item.Dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			return false, err
		}
		if !bytes.Contains(data, []byte("goark:")) {
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), path, data, parser.ParseComments)
		if err != nil {
			return false, err
		}
		for _, group := range file.Comments {
			for _, comment := range group.List {
				if !strings.HasPrefix(comment.Text, "//") {
					continue
				}
				text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
				if strings.HasPrefix(text, "goark:") {
					return true, nil
				}
			}
		}
	}
	return false, nil
}

func writeGeneratedFile(path string, data []byte) (bool, error) {
	path = filepath.Clean(path)
	current, err := os.ReadFile(path)
	switch {
	case err == nil && bytes.Equal(current, data):
		return false, nil
	case err == nil:
	case errors.Is(err, os.ErrNotExist):
	default:
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	mode := generatedFileMode(path)
	temp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return false, err
	}
	tempName := temp.Name()
	renamed := false
	defer func() {
		if !renamed {
			_ = os.Remove(tempName)
		}
	}()
	if _, err := temp.Write(data); err != nil {
		_ = temp.Close()
		return false, err
	}
	if err := temp.Sync(); err != nil {
		_ = temp.Close()
		return false, err
	}
	if err := temp.Close(); err != nil {
		return false, err
	}
	if err := os.Chmod(tempName, mode); err != nil {
		return false, err
	}
	if err := os.Rename(tempName, path); err != nil {
		return false, err
	}
	renamed = true
	return true, nil
}

func generatedFileMode(path string) fs.FileMode {
	info, err := os.Stat(path)
	if err != nil || info.IsDir() {
		return 0o644
	}
	return info.Mode().Perm()
}
