package cli

import (
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestGenerateProject_whenAnnotatedPackageExists_shouldWriteDeterministicSource(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"internal/app/wiring.go": `package app

//goark:service
type UserService struct{}
`,
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}

	results, err := generateProject(project, false)
	if err != nil {
		t.Fatalf("生成项目失败: %v", err)
	}
	if len(results) != 1 || !results[0].Changed {
		t.Fatalf("生成结果错误: %#v", results)
	}
	output := filepath.Join(root, "internal", "app", "zz_goark_app_gen.go")
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("读取生成文件失败: %v", err)
	}
	if !containsAll(string(data), "Code generated by goark", "type GoarkPackageConfiguration struct{}", "userService") {
		t.Fatalf("生成内容错误:\n%s", data)
	}

	oldTime := time.Unix(1_700_000_000, 0)
	if err := os.Chtimes(output, oldTime, oldTime); err != nil {
		t.Fatalf("设置文件时间失败: %v", err)
	}
	results, err = generateProject(project, false)
	if err != nil {
		t.Fatalf("重复生成项目失败: %v", err)
	}
	if len(results) != 1 || !results[0].Changed {
		t.Fatalf("每次生成都应覆盖目标文件: %#v", results)
	}
	info, err := os.Stat(output)
	if err != nil {
		t.Fatalf("读取生成文件状态失败: %v", err)
	}
	if info.ModTime().Equal(oldTime) {
		t.Fatalf("生成文件未被覆盖: %v", info.ModTime())
	}
}

func TestGenerateProject_whenDryRunRequested_shouldNotWriteSource(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"app/wiring.go": `package app

//goark:component
type Component struct{}
`,
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	results, err := generateProject(project, true)
	if err != nil {
		t.Fatalf("模拟生成项目失败: %v", err)
	}
	if len(results) != 1 || results[0].Output == "" {
		t.Fatalf("生成计划错误: %#v", results)
	}
	if _, err := os.Stat(results[0].Output); !os.IsNotExist(err) {
		t.Fatalf("模拟生成不应写入文件: %v", err)
	}
}

func TestGenerateProject_whenMarkerAppearsOnlyInDocumentationOrString_shouldIgnorePackage(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"app/app.go": `package app

// Description mentions //goark:service without declaring an annotation.
const Description = "//goark:component"

/*goark:service*/
type DocumentedType struct{}
`,
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	results, err := generateProject(project, false)
	if err != nil {
		t.Fatalf("生成项目失败: %v", err)
	}
	if len(results) != 0 {
		t.Fatalf("普通文本不应触发生成: %#v", results)
	}
	if _, err := os.Stat(filepath.Join(root, "app", "zz_goark_app_gen.go")); !os.IsNotExist(err) {
		t.Fatalf("普通文本不应产生生成文件: %v", err)
	}
}

func TestGenerateProject_whenGeneratedContentChanges_shouldReplaceExistingFile(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"app/wiring.go": `package app

//goark:service
type UserService struct{}
`,
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	if _, err := generateProject(project, false); err != nil {
		t.Fatalf("首次生成失败: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "app", "wiring.go"), []byte(`package app

//goark:service
type OrderService struct{}
`), 0o644); err != nil {
		t.Fatalf("修改源码失败: %v", err)
	}

	results, err := generateProject(project, false)
	if err != nil {
		t.Fatalf("替换生成文件失败: %v", err)
	}
	if len(results) != 1 || !results[0].Changed {
		t.Fatalf("替换结果错误: %#v", results)
	}
	data, err := os.ReadFile(results[0].Output)
	if err != nil {
		t.Fatalf("读取生成文件失败: %v", err)
	}
	if !strings.Contains(string(data), "orderService") || strings.Contains(string(data), "userService") {
		t.Fatalf("生成内容未替换:\n%s", data)
	}
}

func TestGenerateProject_whenTargetIsNotOwnedGeneratedFile_shouldRejectOverwrite(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"app/wiring.go": `package app

//goark:service
type UserService struct{}
`,
		"app/zz_goark_app_gen.go": "package app\nconst Manual = true\n",
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}

	if _, err := generateProject(project, false); err == nil || !strings.Contains(err.Error(), "不是 Goark 生成文件") {
		t.Fatalf("手写目标文件应阻止覆盖: %v", err)
	}
	data, err := os.ReadFile(filepath.Join(root, "app", "zz_goark_app_gen.go"))
	if err != nil || !strings.Contains(string(data), "const Manual = true") {
		t.Fatalf("手写目标文件被修改: %v\n%s", err, data)
	}
}

func TestGenerateProject_whenInvokedConcurrently_shouldProduceCompleteSource(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25\n",
		"app/wiring.go": `package app

//goark:service
type UserService struct{}
`,
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}

	start := make(chan struct{})
	errorsFound := make(chan error, 8)
	var group sync.WaitGroup
	for range 8 {
		group.Add(1)
		go func() {
			defer group.Done()
			<-start
			_, generateErr := generateProject(project, false)
			errorsFound <- generateErr
		}()
	}
	close(start)
	group.Wait()
	close(errorsFound)
	for generateErr := range errorsFound {
		if generateErr != nil {
			t.Fatalf("并发生成失败: %v", generateErr)
		}
	}
	data, err := os.ReadFile(filepath.Join(root, "app", "zz_goark_app_gen.go"))
	if err != nil {
		t.Fatalf("读取并发生成文件失败: %v", err)
	}
	if !containsAll(string(data), "Code generated by goark", "type GoarkPackageConfiguration struct{}", "userService") {
		t.Fatalf("并发生成内容不完整:\n%s", data)
	}
}

func TestGenerateProject_whenAnnotationsRemoved_shouldRemoveOnlyOwnedGeneratedFile(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod":                        "module example.com/app\n\ngo 1.25\n",
		"app/app.go":                    "package app\ntype Component struct{}\n",
		"app/zz_goark_app_gen.go":       "// Code generated by goark; DO NOT EDIT.\npackage app\n",
		"manual/zz_goark_manual_gen.go": "package manual\nconst Preserved = true\n",
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	results, err := generateProject(project, false)
	if err != nil {
		t.Fatalf("生成项目失败: %v", err)
	}
	if len(results) != 1 || !results[0].Removed {
		t.Fatalf("删除结果错误: %#v", results)
	}
	if _, err := os.Stat(filepath.Join(root, "app", "zz_goark_app_gen.go")); !os.IsNotExist(err) {
		t.Fatalf("陈旧生成文件应删除: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "manual", "zz_goark_manual_gen.go")); err != nil {
		t.Fatalf("手写文件不应删除: %v", err)
	}
}

func TestGenerateProject_whenCleanStaleDisabled_shouldPreserveOwnedGeneratedFile(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod":                  "module example.com/app\n\ngo 1.25\n",
		"app/app.go":              "package app\n",
		"app/zz_goark_app_gen.go": "// Code generated by goark; DO NOT EDIT.\npackage app\n",
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	project.Build.Generate.CleanStale = false

	results, err := generateProject(project, false)
	if err != nil {
		t.Fatalf("生成项目失败: %v", err)
	}
	if len(results) != 0 {
		t.Fatalf("禁用陈旧文件清理时不应报告删除: %#v", results)
	}
	if _, err := os.Stat(filepath.Join(root, "app", "zz_goark_app_gen.go")); err != nil {
		t.Fatalf("禁用陈旧文件清理时应保留生成文件: %v", err)
	}
}

func TestGenerateProject_whenAnnotationsRemovedInDryRun_shouldReportWithoutDeleting(t *testing.T) {
	root := writeTestModule(t, map[string]string{
		"go.mod":                  "module example.com/app\n\ngo 1.25\n",
		"app/app.go":              "package app\n",
		"app/zz_goark_app_gen.go": "// Code generated by goark; DO NOT EDIT.\npackage app\n",
	})
	project, err := newTestProjectResolver(root).Resolve()
	if err != nil {
		t.Fatalf("发现项目失败: %v", err)
	}
	results, err := generateProject(project, true)
	if err != nil {
		t.Fatalf("模拟生成失败: %v", err)
	}
	if len(results) != 1 || !results[0].Removed {
		t.Fatalf("模拟删除结果错误: %#v", results)
	}
	if _, err := os.Stat(results[0].Output); err != nil {
		t.Fatalf("模拟生成不应删除文件: %v", err)
	}
}

func containsAll(value string, fragments ...string) bool {
	for _, fragment := range fragments {
		if !strings.Contains(value, fragment) {
			return false
		}
	}
	return true
}
