package scaffold

import "strconv"

func applicationReadmeTemplate(spec appSpec) string {
	return `# ` + spec.name + `

Goark Boot application generated by the Goark CLI.

## Run

` + "```bash" + `
goark run
` + "```" + `

## Chinese

# ` + spec.name + `（中文）

这是由 Goark CLI 生成的 Goark Boot 应用骨架。

## 运行

` + "```bash" + `
goark run
` + "```" + `
`
}

func applicationGoModTemplate(spec appSpec) string {
	return `module ` + spec.modulePath + `

go 1.27.0

require (
	goark.dev/boot v0.0.1
	goark.dev/gbc-log v0.0.1
	goark.dev/goark v0.0.1
)
`
}

func applicationConfigTemplate(spec appSpec) string {
	return `goark:
  application:
    name: ` + strconv.Quote(spec.name) + `
`
}

func applicationTypeTemplate(web bool) string {
	annotation := "//goark:application"
	if web {
		annotation += "(web=true)"
	}
	return `package app

` + annotation + `
//goark:configuration("app")
type Application struct{}
`
}

func applicationServiceTemplate() string {
	return `package app

// GreetingService 定义应用问候服务。
type GreetingService interface {
	Greeting() string
}

//goark:service("greetingService")
type DefaultGreetingService struct {
	//goark:value("${goark.application.name:goark}")
	ApplicationName string
}

// Greeting 返回包含当前应用名称的问候语。
func (s *DefaultGreetingService) Greeting() string {
	return "Hello from " + s.ApplicationName
}
`
}
