package scaffold

import "strconv"

func applicationReadmeTemplate(spec appSpec) string {
	return `# ` + spec.name + `

Goark Boot application generated by the Goark CLI.

## Run

` + "```bash" + `
go mod tidy
goark run
` + "```" + `

## Chinese

# ` + spec.name + `（中文）

这是由 Goark CLI 生成的 Goark Boot 应用骨架。

## 运行

` + "```bash" + `
go mod tidy
goark run
` + "```" + `
`
}

func applicationGoModTemplate(spec appSpec) string {
	return `module ` + spec.modulePath + `

go 1.25

require (
	goark.dev/boot v0.0.0
	goark.dev/gbc-log v0.0.0
	goark.dev/goark v0.0.0
)
`
}

func applicationConfigTemplate(spec appSpec) string {
	return `goark:
  application:
    name: ` + strconv.Quote(spec.name) + `
  log:
    enabled: true
    install-default: true

logging:
  level:
    root: info
`
}

func applicationGoarkTemplate(spec appSpec) string {
	modulePath := strconv.Quote(spec.modulePath + "/internal/app")
	return `package main

import (
	"context"
	"log/slog"

	app ` + modulePath + `
	"goark.dev/boot"
	"goark.dev/boot/configdata"
	gbclog "goark.dev/gbc-log"
	"goark.dev/goark"
)

func runGoark(args []string) (exitCode int) {
	ctx := context.Background()
	application, err := boot.Run(ctx,
		boot.WithConfigDataOptions(configdata.WithArgs(args...)),
		boot.WithConfiguration(app.Configurations()...),
		boot.WithAutoConfiguration(gbclog.AutoConfigure()),
	)
	if err != nil {
		slog.Error("启动 Goark Boot 应用失败", "error", err)
		return 1
	}
	defer func() {
		if err := application.Close(ctx); err != nil {
			slog.Error("关闭 Goark Boot 应用失败", "error", err)
			exitCode = 1
		}
	}()

	appContext, ok := application.Context()
	if !ok {
		slog.Error("应用上下文尚未初始化")
		return 1
	}
	name := goark.MustGet[string](ctx, appContext, app.BeanNameApplication)
	slog.Info("应用已启动", "name", name)
	return 0
}
`
}

func applicationConfigurationTemplate(spec appSpec) string {
	return `package app

import (
	"context"

	"goark.dev/goark"
	"goark.dev/goark/container"
)

// BeanNameApplication 是应用名称 Bean 的固定名称。
const BeanNameApplication = "applicationName"

// Configurations 返回应用贡献给 Goark Boot 的显式配置单元。
func Configurations() []goark.Configuration {
	return []goark.Configuration{applicationConfiguration{}}
}

type applicationConfiguration struct{}

func (applicationConfiguration) Name() string {
	return "app.core"
}

func (applicationConfiguration) Order() int {
	return 0
}

func (applicationConfiguration) Register(_ context.Context, registry *container.Registry) error {
	return container.RegisterInstance(registry, BeanNameApplication, ` + strconv.Quote(spec.name) + `)
}
`
}
