package scaffold

import "strconv"

func appFiles(spec appSpec) []fileSpec {
	return []fileSpec{
		{path: ".gitignore", content: gitignoreTemplate()},
		{path: "README.md", content: readmeTemplate(spec)},
		{path: "go.mod", content: goModTemplate(spec)},
		{path: "config/app.yml", content: appConfigTemplate(spec)},
		{path: "cmd/server/main.go", content: mainTemplate(spec)},
		{path: "internal/app/configuration.go", content: configurationTemplate()},
	}
}

func gitignoreTemplate() string {
	return `/bin/
/dist/
/tmp/
*.exe
*.test
coverage.out
`
}

func readmeTemplate(spec appSpec) string {
	return `# ` + spec.name + `

Goark Boot Web application generated by the Goark CLI.

## Run

` + "```bash" + `
go mod tidy
go run ./cmd/server
` + "```" + `

The default health endpoint is ` + "`GET /healthz`" + `.

## Chinese

# ` + spec.name + `（中文）

这是由 Goark CLI 生成的 Goark Boot Web 应用骨架。

## 运行

` + "```bash" + `
go mod tidy
go run ./cmd/server
` + "```" + `

默认健康检查端点为 ` + "`GET /healthz`" + `。
`
}

func goModTemplate(spec appSpec) string {
	return `module ` + spec.modulePath + `

go 1.25
`
}

func appConfigTemplate(spec appSpec) string {
	return `goark:
  web:
    application:
      name: ` + strconv.Quote(spec.name) + `
    server:
      address: ":8080"
`
}

func mainTemplate(spec appSpec) string {
	modulePath := strconv.Quote(spec.modulePath + "/internal/app")
	return `package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	app ` + modulePath + `
	"goark.dev/boot"
	"goark.dev/boot/configdata"
	gbcarkhos "goark.dev/gbc-arkhos"
	gbcweb "goark.dev/gbc-web"
	"goark.dev/goark"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	application, err := boot.Run(ctx,
		boot.WithConfigDataOptions(configdata.WithLocations("config")),
		boot.WithConfiguration(app.Configurations()...),
		boot.WithAutoConfiguration(gbcweb.AutoConfigure()),
	)
	if err != nil {
		log.Fatalf("启动 Goark Boot Web 应用失败: %v", err)
	}

	appContext, ok := application.Context()
	if !ok {
		log.Fatal("应用上下文尚未初始化")
	}
	server := goark.MustGet[*gbcarkhos.EmbeddedServer](ctx, appContext, gbcarkhos.BeanNameServer)
	log.Printf("服务已启动: %s", server.URL())

	<-ctx.Done()
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := application.Close(shutdownCtx); err != nil {
		log.Fatalf("关闭 Goark Boot Web 应用失败: %v", err)
	}
}
`
}

func configurationTemplate() string {
	return `package app

import (
	"net/http"

	arkweb "goark.dev/arkarta/web"
	"goark.dev/goark"
	"goark.dev/goark/web/mvc"
)

// Configurations 返回应用贡献给 Goark Boot 的显式配置单元。
func Configurations() []goark.Configuration {
	return []goark.Configuration{
		mvc.NewConfiguration("app.web", mvc.NewController("healthController",
			mvc.GET("/healthz", mvc.JSON(http.StatusOK, func(_ *arkweb.Context) (map[string]string, error) {
				return map[string]string{"status": "UP"}, nil
			})),
		)),
	}
}
`
}
