package scaffold

import "strconv"

func appFiles(spec appSpec) []fileSpec {
	return []fileSpec{
		{path: ".gitignore", content: gitignoreTemplate()},
		{path: "README.md", content: readmeTemplate(spec)},
		{path: "go.mod", content: goModTemplate(spec)},
		{path: "goark.build", content: goarkBuildTemplate(spec)},
		{path: "resource/app.yml", content: appConfigTemplate(spec)},
		{path: "resource/static/index.html", content: staticIndexTemplate(spec)},
		{path: "cmd/server/main.go", content: mainTemplate(spec)},
		{path: "internal/app/configuration.go", content: configurationTemplate()},
	}
}

func goarkBuildTemplate(spec appSpec) string {
	return `# Goark 项目构建描述文件
version = 1

[project]
name = ` + strconv.Quote(spec.name) + `
main = "./cmd/server"

[commands.build]
go-args = ["-trimpath"]
output = "./build/` + spec.name + `"

[commands.test]
go-args = ["./..."]
`
}

func gitignoreTemplate() string {
	return `/bin/
/dist/
/tmp/
/.goark/
*.exe
*.test
coverage.out
`
}

func readmeTemplate(spec appSpec) string {
	return `# ` + spec.name + `

Goark Boot Web application generated by the Goark CLI.

## Run

` + "```bash" + `
go mod tidy
goark run
` + "```" + `

The default health endpoint is ` + "`GET /healthz`" + `.
Static resources are served from ` + "`resource/static`" + ` under ` + "`/static/*`" + `.

## Chinese

# ` + spec.name + `（中文）

这是由 Goark CLI 生成的 Goark Boot Web 应用骨架。

## 运行

` + "```bash" + `
go mod tidy
goark run
` + "```" + `

默认健康检查端点为 ` + "`GET /healthz`" + `。
静态资源默认从 ` + "`resource/static`" + ` 挂载到 ` + "`/static/*`" + `。
`
}

func goModTemplate(spec appSpec) string {
	return `module ` + spec.modulePath + `

go 1.25

require (
	goark.dev/arkarta v0.0.0
	goark.dev/arkhos v0.0.0
	goark.dev/boot v0.0.0
	goark.dev/gbc-arkhos v0.0.0
	goark.dev/gbc-web v0.0.0
	goark.dev/goark v0.0.0
)
`
}

func appConfigTemplate(spec appSpec) string {
	return `goark:
  web:
    application:
      name: ` + strconv.Quote(spec.name) + `
    server:
      address: ":8080"
    client:
      timeout: 5s
      max-response-bytes: 1048576
`
}

func staticIndexTemplate(spec appSpec) string {
	return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>` + spec.name + `</title>
</head>
<body>
  <main>
    <h1>` + spec.name + `</h1>
    <p>Goark Boot Web application is running.</p>
  </main>
</body>
</html>
`
}

func mainTemplate(spec appSpec) string {
	modulePath := strconv.Quote(spec.modulePath + "/internal/app")
	return `package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	app ` + modulePath + `
	"goark.dev/boot"
	gbcarkhos "goark.dev/gbc-arkhos"
	gbcweb "goark.dev/gbc-web"
	"goark.dev/goark"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	application, err := boot.Run(ctx,
		boot.WithConfiguration(app.Configurations()...),
		boot.WithAutoConfiguration(gbcweb.AutoConfigure()),
	)
	if err != nil {
		log.Fatalf("启动 Goark Boot Web 应用失败: %v", err)
	}

	appContext, ok := application.Context()
	if !ok {
		log.Fatal("应用上下文尚未初始化")
	}
	server := goark.MustGet[*gbcarkhos.EmbeddedServer](ctx, appContext, gbcarkhos.BeanNameServer)
	log.Printf("服务已启动: %s", server.URL())

	<-ctx.Done()
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := application.Close(shutdownCtx); err != nil {
		log.Fatalf("关闭 Goark Boot Web 应用失败: %v", err)
	}
}
`
}

func configurationTemplate() string {
	return `package app

import (
	"context"
	"net/http"

	arkweb "goark.dev/arkarta/web"
	gbcweb "goark.dev/gbc-web"
	"goark.dev/goark"
	"goark.dev/goark/container"
	"goark.dev/goark/web/mvc"
	webclient "goark.dev/goark/web/client"
)

// Configurations 返回应用贡献给 Goark Boot 的显式配置单元。
func Configurations() []goark.Configuration {
	return []goark.Configuration{
		webClientConfiguration{},
		mvc.NewConfiguration("app.web", mvc.NewController("healthController",
			mvc.GET("/healthz", mvc.JSON(http.StatusOK, func(_ *arkweb.Context) (map[string]string, error) {
				return map[string]string{"status": "UP"}, nil
			})),
		)),
	}
}

type webClientConfiguration struct{}

func (webClientConfiguration) Name() string {
	return "app.web.client"
}

func (webClientConfiguration) Order() int {
	return 0
}

func (c webClientConfiguration) Register(ctx context.Context, registry *container.Registry) error {
	return c.RegisterWithContext(ctx, goark.NewConfigurationContext(nil, registry))
}

func (webClientConfiguration) RegisterWithContext(_ context.Context, config goark.ConfigurationContext) error {
	return gbcweb.RegisterHTTPClientBuilderCustomizer(config.Registry(), "appHTTPClientCustomizer", gbcweb.HTTPClientBuilderCustomizerFunc(func(ctx context.Context, builder *webclient.Builder) (*webclient.Builder, error) {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		return builder.DefaultHeader("X-Goark-App", "true"), nil
	}))
}
`
}
