package scaffold

import "strconv"

func appFiles(spec appSpec) []fileSpec {
	files := []fileSpec{
		{path: ".gitignore", content: gitignoreTemplate()},
		{path: "goark.build", content: goarkBuildTemplate(spec)},
	}
	if spec.projectType == ProjectTypeApp {
		return append(
			files,
			fileSpec{path: "README.md", content: applicationReadmeTemplate(spec)},
			fileSpec{path: "go.mod", content: applicationGoModTemplate(spec)},
			fileSpec{path: "resource/app.yml", content: applicationConfigTemplate(spec)},
			fileSpec{path: "cmd/app/main.go", content: minimalMainTemplate(spec)},
			fileSpec{path: "internal/app/application.go", content: applicationTypeTemplate(false)},
			fileSpec{path: "internal/app/service.go", content: applicationServiceTemplate()},
		)
	}
	return append(files,
		fileSpec{path: "README.md", content: webReadmeTemplate(spec)},
		fileSpec{path: "go.mod", content: webGoModTemplate(spec)},
		fileSpec{path: "resource/app.yml", content: webConfigTemplate(spec)},
		fileSpec{path: "resource/static/index.html", content: staticIndexTemplate(spec)},
		fileSpec{path: "cmd/server/main.go", content: minimalMainTemplate(spec)},
		fileSpec{path: "internal/app/application.go", content: applicationTypeTemplate(true)},
		fileSpec{path: "internal/app/service.go", content: applicationServiceTemplate()},
		fileSpec{path: "internal/app/controller.go", content: webControllerTemplate()},
	)
}

func minimalMainTemplate(spec appSpec) string {
	return `package main

import (
	"os"

	appgen "` + spec.modulePath + `/internal/app/gen"
)

func main() {
	os.Exit(appgen.Run(os.Args[1:]))
}
`
}

func goarkBuildTemplate(spec appSpec) string {
	mainPackage := "./cmd/app"
	if spec.projectType == ProjectTypeWeb {
		mainPackage = "./cmd/server"
	}
	return `# Goark 项目构建描述文件
version = 1

[project]
name = ` + strconv.Quote(spec.name) + `
main = ` + strconv.Quote(mainPackage) + `

[commands.build]
go-args = ["-trimpath"]
output = "./build/` + spec.name + `"

[commands.test]
go-args = ["./..."]
`
}

func gitignoreTemplate() string {
	return `/bin/
/dist/
/tmp/
/.goark/
**/gen/
*.exe
*.test
coverage.out
`
}

func webReadmeTemplate(spec appSpec) string {
	return `# ` + spec.name + `

Goark Boot Web application generated by the Goark CLI.

## Run

` + "```bash" + `
goark run
` + "```" + `

The default health endpoint is ` + "`GET /healthz`" + `.
Static resources are served from ` + "`resource/static`" + ` under ` + "`/static/*`" + `.

## Chinese

# ` + spec.name + `（中文）

这是由 Goark CLI 生成的 Goark Boot Web 应用骨架。

## 运行

` + "```bash" + `
goark run
` + "```" + `

默认健康检查端点为 ` + "`GET /healthz`" + `。
静态资源默认从 ` + "`resource/static`" + ` 挂载到 ` + "`/static/*`" + `。
`
}

func webGoModTemplate(spec appSpec) string {
	return `module ` + spec.modulePath + `

go 1.27.0

require (
	goark.dev/arkarta v0.0.3
	goark.dev/boot v0.0.1
	goark.dev/gbc-arkhos v0.0.1
	goark.dev/gbc-log v0.0.1
	goark.dev/gbc-web v0.0.1
	goark.dev/goark v0.0.1
)
`
}

func webConfigTemplate(spec appSpec) string {
	return `goark:
  application:
    name: ` + strconv.Quote(spec.name) + `
`
}

func staticIndexTemplate(spec appSpec) string {
	return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>` + spec.name + `</title>
</head>
<body>
  <main>
    <h1>` + spec.name + `</h1>
    <p>Goark Boot Web application is running.</p>
  </main>
</body>
</html>
`
}

func webControllerTemplate() string {
	return `package app

//goark-web:rest-controller("greetingController")
type GreetingController struct {
	//goark:autowired
	//goark:qualifier("greetingService")
	Service GreetingService
}

// Health 返回应用健康状态和服务问候语。
//goark-web:get("/healthz")
func (c *GreetingController) Health() map[string]string {
	return map[string]string{
		"message": c.Service.Greeting(),
		"status":  "UP",
	}
}
`
}
