package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"goark.dev/cli/internal/generate/annotationparse"
)

func scanInterfaceMethods(
	ctx *AnnotationBindingContext, pipeline *annotationPipeline,
	fset *token.FileSet, file *ast.File, decl *ast.GenDecl,
	typeSpec *ast.TypeSpec, interfaceType *ast.InterfaceType,
) error {
	for _, method := range interfaceType.Methods.List {
		methodAnnotations, err := parseAnnotations(method.Doc)
		if err != nil {
			return err
		}
		if len(methodAnnotations) == 0 {
			continue
		}
		item := AnnotationItem{
			target:      AnnotationTargetMethod,
			packageName: ctx.PackageName(),
			fset:        fset,
			file:        file,
			genDecl:     decl,
			typeSpec:    typeSpec,
			field:       method,
			annotations: methodAnnotations,
		}
		if err := pipeline.dispatch(ctx, item); err != nil {
			return err
		}
	}
	return nil
}

func (p *annotationPipeline) dispatch(ctx *AnnotationBindingContext, item AnnotationItem) error {
	if err := p.validate(item); err != nil {
		return err
	}
	for _, extension := range p.extensions {
		if extension.Binder == nil || !itemMatchesDescriptors(item, extension.Descriptors) {
			continue
		}
		if err := extension.Binder.BindAnnotation(ctx, item); err != nil {
			return err
		}
	}
	return nil
}

func (p *annotationPipeline) validate(item AnnotationItem) error {
	for _, annotation := range item.annotations {
		descriptor, ok := p.descriptors[annotation.Name]
		if !ok {
			return fmt.Errorf("unknown annotation %q", annotation.Name)
		}
		if !descriptorAllowsTarget(descriptor, item.Target()) {
			return annotationError("does not support %s target", annotation.Name, item.Target())
		}
		if descriptor.Validate == nil {
			continue
		}
		ctx := AnnotationValidationContext{
			Target:     item.Target(),
			Annotation: annotation,
			Item:       item,
		}
		if err := descriptor.Validate(ctx); err != nil {
			return err
		}
	}
	return nil
}

func descriptorAllowsTarget(descriptor AnnotationDescriptor, target AnnotationTarget) bool {
	if len(descriptor.Targets) == 0 {
		return true
	}
	for _, item := range descriptor.Targets {
		if item == target {
			return true
		}
	}
	return false
}

func itemMatchesDescriptors(item AnnotationItem, descriptors []AnnotationDescriptor) bool {
	for _, descriptor := range descriptors {
		if item.HasAnnotation(descriptor.Name) {
			return true
		}
	}
	return false
}

func renderAnnotationExtensions(
	pkg *annotationPackage,
	values map[string]any,
	pipeline *annotationPipeline,
	extensions []AnnotationExtension,
) ([]byte, error) {
	ctx := &AnnotationGenerationContext{
		pkg:        pkg,
		values:     values,
		importKeys: make(map[string]struct{}),
	}
	if pkg.SourceImportPath != "" {
		ctx.AddImport(sourcePackageAlias, pkg.SourceImportPath)
	}
	for _, extension := range extensions {
		if extension.Generator == nil {
			continue
		}
		if err := extension.Generator.GenerateAnnotation(ctx); err != nil {
			return nil, err
		}
	}
	if ctx.body.Len() == 0 {
		return nil, nil
	}

	var builder bytes.Buffer
	builder.WriteString("// Code generated by goark; DO NOT EDIT.\n")
	builder.WriteString("// Goark CLI 版本: ")
	builder.WriteString(pipeline.spec.GeneratorVersion)
	builder.WriteString("\n// 来源包: ")
	builder.WriteString(pipeline.spec.SourceImportPath)
	builder.WriteString("\n// 生成命令: goark generate\n\n")
	builder.WriteString("package ")
	if pkg.SourceImportPath == "" {
		builder.WriteString(pkg.PackageName)
	} else {
		builder.WriteString("gen")
	}
	builder.WriteString("\n\n")
	writeAnnotationImports(&builder, ctx.imports)
	builder.Write(ctx.body.Bytes())
	formatted, err := format.Source(builder.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated annotations: %w\n%s", err, builder.String())
	}
	return formatted, nil
}

func writeAnnotationImports(builder *bytes.Buffer, imports []ImportSpec) {
	if len(imports) == 0 {
		return
	}
	sortImports(imports)
	builder.WriteString("import (\n")
	for _, item := range imports {
		if item.Alias != "" {
			builder.WriteString(item.Alias)
			builder.WriteByte(' ')
		}
		builder.WriteString(strconv.Quote(item.Path))
		builder.WriteByte('\n')
	}
	builder.WriteString(")\n\n")
}

// DefaultAnnotationOutputName 返回注解扫描默认输出文件名。
func DefaultAnnotationOutputName(packageName string) string {
	packageName = strings.TrimSpace(packageName)
	if packageName == "" {
		packageName = "package"
	}
	return filepath.Clean("zz_goark_" + packageName + "_gen.go")
}

type annotationPackage struct {
	PackageName      string
	SourceImportPath string
	fset             *token.FileSet
	types            map[string]annotationTypeDeclaration
}

type annotationTypeDeclaration struct {
	file *ast.File
	spec *ast.TypeSpec
}

// GenerateAnnotations 扫描 Go 源码注解并生成 goark 注册代码。
func GenerateAnnotations(spec AnnotationScanSpec) ([]byte, error) {
	pkg, values, pipeline, err := buildAnnotationModel(spec)
	if err != nil {
		return nil, err
	}
	return renderAnnotationExtensions(pkg, values, pipeline, pipeline.extensions)
}

// AnnotationFile 描述一个按职责拆分的注解生成文件。
type AnnotationFile struct {
	Name   string
	Source []byte
}

// GenerateAnnotationFiles 扫描一次源码，并按生成职责输出独立文件。
func GenerateAnnotationFiles(spec AnnotationScanSpec) ([]AnnotationFile, error) {
	pkg, values, pipeline, err := buildAnnotationModel(spec)
	if err != nil {
		return nil, err
	}
	files := make([]AnnotationFile, 0, len(pipeline.extensions))
	for index, extension := range pipeline.extensions {
		if extension.Generator == nil {
			continue
		}
		source, err := renderAnnotationExtensions(pkg, values, pipeline, []AnnotationExtension{extension})
		if err != nil {
			return nil, err
		}
		if source == nil {
			continue
		}
		name := strings.TrimSpace(extension.Name)
		if name == "" {
			name = fmt.Sprintf("extension_%02d", index+1)
		}
		files = append(files, AnnotationFile{
			Name:   "zz_goark_" + name + "_gen.go",
			Source: source,
		})
	}
	return files, nil
}

func buildAnnotationModel(
	spec AnnotationScanSpec,
) (*annotationPackage, map[string]any, *annotationPipeline, error) {
	pipeline, err := newAnnotationPipeline(spec)
	if err != nil {
		return nil, nil, nil, err
	}
	pkg, values, err := scanAnnotations(spec, pipeline)
	if err != nil {
		return nil, nil, nil, err
	}
	if err := prepareExternalGeneration(pkg, values); err != nil {
		return nil, nil, nil, err
	}
	return pkg, values, pipeline, nil
}

func newAnnotationPipeline(spec AnnotationScanSpec) (*annotationPipeline, error) {
	all := append(defaultAnnotationExtensions(), spec.Extensions...)
	pipeline := &annotationPipeline{
		extensions:  all,
		descriptors: make(map[string]AnnotationDescriptor),
		spec:        spec,
	}
	for _, extension := range all {
		for _, descriptor := range extension.Descriptors {
			name := strings.TrimSpace(descriptor.Name)
			if name == "" {
				return nil, fmt.Errorf("annotation descriptor name is required")
			}
			if _, exists := pipeline.descriptors[name]; exists {
				return nil, fmt.Errorf("duplicate annotation descriptor %q", name)
			}
			descriptor.Name = name
			pipeline.descriptors[name] = descriptor
		}
	}
	return pipeline, nil
}

func scanAnnotations(
	spec AnnotationScanSpec,
	pipeline *annotationPipeline,
) (*annotationPackage, map[string]any, error) {
	dir := strings.TrimSpace(spec.Dir)
	if dir == "" {
		dir = "."
	}
	fset := token.NewFileSet()
	packages, err := annotationparse.ParsePackages(fset, dir, spec.Files)
	if err != nil {
		return nil, nil, err
	}
	if len(packages) == 0 {
		return nil, nil, fmt.Errorf("no Go package found in %s", dir)
	}
	packageNames := make([]string, 0, len(packages))
	for name := range packages {
		packageNames = append(packageNames, name)
	}
	sort.Strings(packageNames)
	packageName := strings.TrimSpace(spec.PackageName)
	if packageName == "" {
		if len(packageNames) != 1 {
			return nil, nil, fmt.Errorf(
				"multiple Go packages found in %s: %s",
				dir,
				strings.Join(packageNames, ", "),
			)
		}
		packageName = packageNames[0]
	}
	parsedPackage := packages[packageName]
	if parsedPackage == nil {
		return nil, nil, fmt.Errorf("package %q not found in %s", packageName, dir)
	}

	pkg := &annotationPackage{
		PackageName:      packageName,
		SourceImportPath: strings.TrimSpace(spec.SourceImportPath),
		fset:             fset,
		types:            make(map[string]annotationTypeDeclaration),
	}
	for _, file := range parsedPackage.Files {
		for _, declaration := range file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.TYPE {
				continue
			}
			for _, item := range general.Specs {
				typeSpec, ok := item.(*ast.TypeSpec)
				if ok {
					pkg.types[typeSpec.Name.Name] = annotationTypeDeclaration{file: file, spec: typeSpec}
				}
			}
		}
	}
	ctx := &AnnotationBindingContext{
		spec:   spec,
		pkg:    pkg,
		values: make(map[string]any),
	}
	files := annotationparse.SortedFiles(fset, parsedPackage)
	for _, file := range files {
		if err := scanAnnotationFile(ctx, pipeline, fset, file); err != nil {
			return nil, nil, err
		}
	}
	for _, extension := range pipeline.extensions {
		finalizer, ok := extension.Binder.(annotationBindingFinalizer)
		if !ok {
			continue
		}
		if err := finalizer.FinalizeAnnotationBinding(ctx); err != nil {
			return nil, nil, err
		}
	}
	return pkg, ctx.values, nil
}
