package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strconv"
	"strings"
)

func renderAnnotationPackage(pkg *annotationPackage, values map[string]any, pipeline *annotationPipeline) ([]byte, error) {
	ctx := &AnnotationGenerationContext{
		pkg:        pkg,
		values:     values,
		importKeys: make(map[string]struct{}),
	}
	for _, extension := range pipeline.extensions {
		if extension.Generator == nil {
			continue
		}
		if err := extension.Generator.GenerateAnnotation(ctx); err != nil {
			return nil, err
		}
	}

	var builder bytes.Buffer
	builder.WriteString("// Code generated by goark; DO NOT EDIT.\n")
	builder.WriteString("// 本文件由 goark 注解扫描生成，请勿手工修改。\n\n")
	builder.WriteString("package ")
	builder.WriteString(pkg.PackageName)
	builder.WriteString("\n\n")
	writeAnnotationImports(&builder, ctx.imports)
	builder.Write(ctx.body.Bytes())
	formatted, err := format.Source(builder.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated annotations: %w\n%s", err, builder.String())
	}
	return formatted, nil
}

func writeAnnotationImports(builder *bytes.Buffer, imports []ImportSpec) {
	if len(imports) == 0 {
		return
	}
	sortImports(imports)
	builder.WriteString("import (\n")
	for _, item := range imports {
		if item.Alias != "" {
			builder.WriteString(item.Alias)
			builder.WriteByte(' ')
		}
		builder.WriteString(strconv.Quote(item.Path))
		builder.WriteByte('\n')
	}
	builder.WriteString(")\n\n")
}

// DefaultAnnotationOutputName 返回注解扫描默认输出文件名。
func DefaultAnnotationOutputName(packageName string) string {
	packageName = strings.TrimSpace(packageName)
	if packageName == "" {
		packageName = "package"
	}
	return filepath.Clean("zz_goark_" + packageName + "_gen.go")
}
