package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// ConfigurationSpec 描述 goark.Configuration 生成输入。
type ConfigurationSpec struct {
	PackageName       string
	ConfigurationName string
	TypeName          string
	Order             int
	Imports           []ImportSpec
	Beans             []BeanSpec
}

// ImportSpec 描述生成文件所需的额外导入。
type ImportSpec struct {
	Alias string
	Path  string
}

// BeanSpec 描述一个显式 Bean 注册项。
type BeanSpec struct {
	Name         string
	Provider     string
	Dependencies []string
	Scope        string
	Lazy         bool
	Primary      bool
}

const (
	// ScopeSingleton 表示单例 Bean。
	ScopeSingleton = "singleton"
	// ScopePrototype 表示原型 Bean。
	ScopePrototype = "prototype"
)

// GenerateConfiguration 生成 goark.Configuration 源码。
func GenerateConfiguration(spec ConfigurationSpec) ([]byte, error) {
	if err := validateConfigurationSpec(&spec); err != nil {
		return nil, err
	}

	var builder bytes.Buffer
	builder.WriteString("// Code generated by goark; DO NOT EDIT.\n")
	builder.WriteString("// 本文件由 goark 生成，请勿手工修改。\n\n")
	builder.WriteString("package ")
	builder.WriteString(spec.PackageName)
	builder.WriteString("\n\n")
	writeImports(&builder, spec.Imports)
	writeConfigurationType(&builder, spec)
	writeConfigurationRegister(&builder, spec)

	formatted, err := format.Source(builder.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated configuration: %w", err)
	}
	return formatted, nil
}

func validateConfigurationSpec(spec *ConfigurationSpec) error {
	spec.PackageName = strings.TrimSpace(spec.PackageName)
	spec.ConfigurationName = strings.TrimSpace(spec.ConfigurationName)
	spec.TypeName = strings.TrimSpace(spec.TypeName)
	if spec.PackageName == "" {
		return fmt.Errorf("package name is required")
	}
	if !isIdentifier(spec.PackageName) {
		return fmt.Errorf("invalid package name %q", spec.PackageName)
	}
	if spec.ConfigurationName == "" {
		return fmt.Errorf("configuration name is required")
	}
	if spec.TypeName == "" {
		spec.TypeName = ToPascalIdentifier(spec.ConfigurationName) + "Configuration"
	}
	if !isExportedIdentifier(spec.TypeName) {
		return fmt.Errorf("configuration type must be an exported Go identifier, got %q", spec.TypeName)
	}
	if err := validateImports(spec.Imports); err != nil {
		return err
	}
	for index := range spec.Beans {
		if err := validateBeanSpec(&spec.Beans[index]); err != nil {
			return err
		}
	}
	sortImports(spec.Imports)
	sortBeans(spec.Beans)
	return nil
}

func validateImports(imports []ImportSpec) error {
	seen := make(map[string]struct{}, len(imports))
	for index := range imports {
		item := &imports[index]
		path := strings.TrimSpace(item.Path)
		if path == "" {
			return fmt.Errorf("import path is required")
		}
		if strings.ContainsAny(path, "\"\n\r\t") {
			return fmt.Errorf("invalid import path %q", path)
		}
		alias := strings.TrimSpace(item.Alias)
		if alias != "" && alias != "." && alias != "_" && !isIdentifier(alias) {
			return fmt.Errorf("invalid import alias %q", alias)
		}
		key := alias + "\x00" + path
		if _, exists := seen[key]; exists {
			return fmt.Errorf("duplicate import %q", path)
		}
		item.Alias = alias
		item.Path = path
		seen[key] = struct{}{}
	}
	return nil
}

func validateBeanSpec(bean *BeanSpec) error {
	bean.Name = strings.TrimSpace(bean.Name)
	bean.Provider = strings.TrimSpace(bean.Provider)
	bean.Scope = strings.TrimSpace(bean.Scope)
	if bean.Name == "" {
		return fmt.Errorf("bean name is required")
	}
	if bean.Provider == "" {
		return fmt.Errorf("bean %q provider is required", bean.Name)
	}
	switch bean.Scope {
	case "", ScopeSingleton, ScopePrototype:
	default:
		return fmt.Errorf("bean %q has unsupported scope %q", bean.Name, bean.Scope)
	}
	for i, dependency := range bean.Dependencies {
		dependency = strings.TrimSpace(dependency)
		if dependency == "" {
			return fmt.Errorf("bean %q has empty dependency", bean.Name)
		}
		bean.Dependencies[i] = dependency
	}
	return nil
}

func writeImports(builder *bytes.Buffer, imports []ImportSpec) {
	builder.WriteString("import (\n")
	builder.WriteString(strconv.Quote("context"))
	builder.WriteString("\n\n")
	builder.WriteString(strconv.Quote("goark.dev/goark/container"))
	builder.WriteByte('\n')
	for _, item := range imports {
		if item.Alias != "" {
			builder.WriteString(item.Alias)
			builder.WriteByte(' ')
		}
		builder.WriteString(strconv.Quote(item.Path))
		builder.WriteByte('\n')
	}
	builder.WriteString(")\n\n")
}

func writeConfigurationType(builder *bytes.Buffer, spec ConfigurationSpec) {
	builder.WriteString("type ")
	builder.WriteString(spec.TypeName)
	builder.WriteString(" struct{}\n\n")
	builder.WriteString("func (")
	builder.WriteString(spec.TypeName)
	builder.WriteString(") Name() string {\nreturn ")
	builder.WriteString(strconv.Quote(spec.ConfigurationName))
	builder.WriteString("\n}\n\n")
	builder.WriteString("func (")
	builder.WriteString(spec.TypeName)
	builder.WriteString(") Order() int {\nreturn ")
	builder.WriteString(strconv.Itoa(spec.Order))
	builder.WriteString("\n}\n\n")
}

func writeConfigurationRegister(builder *bytes.Buffer, spec ConfigurationSpec) {
	builder.WriteString("func (")
	builder.WriteString(spec.TypeName)
	builder.WriteString(") Register(ctx context.Context, registry *container.Registry) error {\n")
	builder.WriteString("_ = ctx\n")
	for _, bean := range spec.Beans {
		writeBeanRegistration(builder, bean)
	}
	builder.WriteString("return nil\n")
	builder.WriteString("}\n")
}

func writeBeanRegistration(builder *bytes.Buffer, bean BeanSpec) {
	builder.WriteString("if err := container.Register(registry, ")
	builder.WriteString(strconv.Quote(bean.Name))
	builder.WriteString(", ")
	builder.WriteString(bean.Provider)
	for _, option := range beanOptions(bean) {
		builder.WriteString(", ")
		builder.WriteString(option)
	}
	builder.WriteString("); err != nil {\nreturn err\n}\n")
}

func beanOptions(bean BeanSpec) []string {
	options := make([]string, 0, 4)
	if bean.Scope == ScopePrototype {
		options = append(options, "container.WithPrototype()")
	}
	if bean.Lazy {
		options = append(options, "container.WithLazy()")
	}
	if bean.Primary {
		options = append(options, "container.WithPrimary()")
	}
	if len(bean.Dependencies) > 0 {
		quoted := make([]string, 0, len(bean.Dependencies))
		for _, dependency := range bean.Dependencies {
			quoted = append(quoted, strconv.Quote(dependency))
		}
		options = append(options, "container.WithDependencies("+strings.Join(quoted, ", ")+")")
	}
	return options
}

func sortImports(imports []ImportSpec) {
	sort.SliceStable(imports, func(i, j int) bool {
		if imports[i].Path == imports[j].Path {
			return imports[i].Alias < imports[j].Alias
		}
		return imports[i].Path < imports[j].Path
	})
}

func sortBeans(beans []BeanSpec) {
	sort.SliceStable(beans, func(i, j int) bool {
		return beans[i].Name < beans[j].Name
	})
}

func isIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, r := range value {
		if index == 0 {
			if r != '_' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

func isExportedIdentifier(value string) bool {
	if !isIdentifier(value) {
		return false
	}
	r, _ := utf8.DecodeRuneInString(value)
	return unicode.IsUpper(r)
}

// ToPascalIdentifier 将配置名称转换为导出类型名片段。
func ToPascalIdentifier(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '-' || r == '_' || r == '.' || r == '/' || unicode.IsSpace(r)
	})
	var builder strings.Builder
	for _, part := range parts {
		for i, r := range part {
			if i == 0 {
				builder.WriteRune(unicode.ToUpper(r))
				continue
			}
			builder.WriteRune(r)
		}
	}
	if builder.Len() == 0 {
		return "Generated"
	}
	return builder.String()
}
