package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"sort"
	"strconv"
	"strings"
)

const goarkImportPath = "github.com/goark-projects/goark"

// RegistrySpec 描述 Configuration 注册表生成输入。
type RegistrySpec struct {
	PackageName    string
	FunctionName   string
	Imports        []ImportSpec
	Configurations []ConfigurationRegistrationSpec
}

// ConfigurationRegistrationSpec 描述一个待注册的配置类型。
type ConfigurationRegistrationSpec struct {
	Type string
}

// GenerateRegistry 生成 Configuration 注册表源码。
func GenerateRegistry(spec RegistrySpec) ([]byte, error) {
	if err := validateRegistrySpec(&spec); err != nil {
		return nil, err
	}

	var builder bytes.Buffer
	builder.WriteString("// Code generated by goark; DO NOT EDIT.\n")
	builder.WriteString("// 本文件由 goark 生成，请勿手工修改。\n\n")
	builder.WriteString("package ")
	builder.WriteString(spec.PackageName)
	builder.WriteString("\n\n")
	writeRegistryImports(&builder, spec.Imports)
	writeRegistryFunction(&builder, spec)

	formatted, err := format.Source(builder.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated registry: %w", err)
	}
	return formatted, nil
}

func validateRegistrySpec(spec *RegistrySpec) error {
	spec.PackageName = strings.TrimSpace(spec.PackageName)
	spec.FunctionName = strings.TrimSpace(spec.FunctionName)
	if spec.PackageName == "" {
		return fmt.Errorf("package name is required")
	}
	if !isIdentifier(spec.PackageName) {
		return fmt.Errorf("invalid package name %q", spec.PackageName)
	}
	if spec.FunctionName == "" {
		spec.FunctionName = "RegisterConfigurations"
	}
	if !isIdentifier(spec.FunctionName) {
		return fmt.Errorf("registry function must be a Go identifier, got %q", spec.FunctionName)
	}
	if len(spec.Configurations) == 0 {
		return fmt.Errorf("at least one configuration is required")
	}
	if err := validateImports(spec.Imports); err != nil {
		return err
	}
	for _, item := range spec.Imports {
		if strings.TrimSpace(item.Path) == goarkImportPath {
			return fmt.Errorf("import %q is reserved by the registry generator", goarkImportPath)
		}
	}
	for index := range spec.Configurations {
		if err := validateConfigurationRegistrationSpec(&spec.Configurations[index]); err != nil {
			return err
		}
	}
	sortImports(spec.Imports)
	sortConfigurationRegistrations(spec.Configurations)
	return nil
}

func validateConfigurationRegistrationSpec(spec *ConfigurationRegistrationSpec) error {
	spec.Type = strings.TrimSpace(spec.Type)
	if spec.Type == "" {
		return fmt.Errorf("configuration type is required")
	}
	if strings.ContainsAny(spec.Type, "\n\r") {
		return fmt.Errorf("invalid configuration type %q", spec.Type)
	}
	expr, err := parser.ParseExpr(spec.Type)
	if err != nil {
		return fmt.Errorf("invalid configuration type %q: %w", spec.Type, err)
	}
	if !isConfigurationTypeExpression(expr) {
		return fmt.Errorf("invalid configuration type %q", spec.Type)
	}
	return nil
}

func isConfigurationTypeExpression(expr ast.Expr) bool {
	switch item := expr.(type) {
	case *ast.Ident:
		return isExportedIdentifier(item.Name)
	case *ast.SelectorExpr:
		packageName, ok := item.X.(*ast.Ident)
		return ok && isIdentifier(packageName.Name) && isExportedIdentifier(item.Sel.Name)
	default:
		return false
	}
}

func writeRegistryImports(builder *bytes.Buffer, imports []ImportSpec) {
	builder.WriteString("import (\n")
	builder.WriteString(strconv.Quote(goarkImportPath))
	builder.WriteByte('\n')
	for _, item := range imports {
		if item.Alias != "" {
			builder.WriteString(item.Alias)
			builder.WriteByte(' ')
		}
		builder.WriteString(strconv.Quote(item.Path))
		builder.WriteByte('\n')
	}
	builder.WriteString(")\n\n")
}

func writeRegistryFunction(builder *bytes.Buffer, spec RegistrySpec) {
	builder.WriteString("func ")
	builder.WriteString(spec.FunctionName)
	builder.WriteString("(app *goark.ApplicationContext) error {\n")
	for _, configuration := range spec.Configurations {
		builder.WriteString("if err := goark.RegisterConfiguration(app, ")
		builder.WriteString(configuration.Type)
		builder.WriteString("{}); err != nil {\nreturn err\n}\n")
	}
	builder.WriteString("return nil\n")
	builder.WriteString("}\n")
}

func sortConfigurationRegistrations(configurations []ConfigurationRegistrationSpec) {
	sort.SliceStable(configurations, func(i, j int) bool {
		return configurations[i].Type < configurations[j].Type
	})
}
